name: 'Continuous Integration'

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0", "8.1", "8.2", "8.3"]
    steps:
      -
        name: 'Checkout The Code'
        uses: actions/checkout@v4
      -
        name: 'Install Dependencies'
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"
      - name: 'Unit Tests'
        uses: php-actions/phpunit@v4
        with:
          php_version: "${{ matrix.php }}"
